version: '3.9'

services:
  app:
    depends_on:
      - redis
      - dev-db
    build:
      dockerfile: Dockerfile
      context: './'
    ports:
      - "4000:4000"
    restart: always
    networks:
      - nest-js

  nginx1: 
    restart: always
    build:
      dockerfile: Dockerfile
      context: './nginx'
    ports:
      - "8002:80"
    networks:
      - nest-js
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - nest-js

  dev-db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    # volumes:
    #   - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nest
    networks:
      - nest-js
networks:
  nest-js:
    driver: bridge